# Generated by Django 3.0.5 on 2020-05-14 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracker', '0003_auto_20200429_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountshares',
            name='peak_pct_of_balance',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountshares',
            name='trough_pct_of_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accountshares',
            name='pct_of_peak',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountshares',
            name='peak_date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
    ]
