# Generated by Django 3.0.5 on 2020-05-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracker', '0005_auto_20200514_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountshares',
            name='pct_of_peak',
        ),
        migrations.RemoveField(
            model_name='accountshares',
            name='pct_of_trough',
        ),
    ]
