# Generated by Django 3.0.5 on 2020-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracker', '0006_auto_20200514_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='money_market',
            field=models.BooleanField(default=False),
        ),
    ]
