# Generated by Django 3.2.8 on 2021-10-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracker', '0007_fund_money_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tag',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
