# Generated by Django 3.2.8 on 2021-10-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracker', '0008_plan_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylink',
            name='tag',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
